// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pcounter.proto

package proto_pcounter // import "github.com/synerex/proto_pcounter"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// People Counter Service message
type PCounter struct {
	DeviceId             string               `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Hostname             string               `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Location             string               `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Timezone             string               `protobuf:"bytes,4,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Mac                  string               `protobuf:"bytes,5,opt,name=mac,proto3" json:"mac,omitempty"`
	Hardware             string               `protobuf:"bytes,6,opt,name=hardware,proto3" json:"hardware,omitempty"`
	Protocol             string               `protobuf:"bytes,7,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Ts                   *timestamp.Timestamp `protobuf:"bytes,8,opt,name=ts,proto3" json:"ts,omitempty"`
	Data                 []*PEvent            `protobuf:"bytes,9,rep,name=data,proto3" json:"data,omitempty"`
	Areas                []*PArea             `protobuf:"bytes,10,rep,name=areas,proto3" json:"areas,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PCounter) Reset()         { *m = PCounter{} }
func (m *PCounter) String() string { return proto.CompactTextString(m) }
func (*PCounter) ProtoMessage()    {}
func (*PCounter) Descriptor() ([]byte, []int) {
	return fileDescriptor_pcounter_42299f20fff80161, []int{0}
}
func (m *PCounter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PCounter.Unmarshal(m, b)
}
func (m *PCounter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PCounter.Marshal(b, m, deterministic)
}
func (dst *PCounter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PCounter.Merge(dst, src)
}
func (m *PCounter) XXX_Size() int {
	return xxx_messageInfo_PCounter.Size(m)
}
func (m *PCounter) XXX_DiscardUnknown() {
	xxx_messageInfo_PCounter.DiscardUnknown(m)
}

var xxx_messageInfo_PCounter proto.InternalMessageInfo

func (m *PCounter) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *PCounter) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *PCounter) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *PCounter) GetTimezone() string {
	if m != nil {
		return m.Timezone
	}
	return ""
}

func (m *PCounter) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func (m *PCounter) GetHardware() string {
	if m != nil {
		return m.Hardware
	}
	return ""
}

func (m *PCounter) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *PCounter) GetTs() *timestamp.Timestamp {
	if m != nil {
		return m.Ts
	}
	return nil
}

func (m *PCounter) GetData() []*PEvent {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *PCounter) GetAreas() []*PArea {
	if m != nil {
		return m.Areas
	}
	return nil
}

type PEvent struct {
	Typ                  string               `protobuf:"bytes,1,opt,name=typ,proto3" json:"typ,omitempty"`
	Id                   string               `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Seq                  uint32               `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Height               uint32               `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Dir                  string               `protobuf:"bytes,5,opt,name=dir,proto3" json:"dir,omitempty"`
	Ts                   *timestamp.Timestamp `protobuf:"bytes,6,opt,name=ts,proto3" json:"ts,omitempty"`
	FillLevel            string               `protobuf:"bytes,7,opt,name=fillLevel,proto3" json:"fillLevel,omitempty"`
	DwellTime            string               `protobuf:"bytes,8,opt,name=dwellTime,proto3" json:"dwellTime,omitempty"`
	ExpDwellTime         string               `protobuf:"bytes,9,opt,name=expDwellTime,proto3" json:"expDwellTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PEvent) Reset()         { *m = PEvent{} }
func (m *PEvent) String() string { return proto.CompactTextString(m) }
func (*PEvent) ProtoMessage()    {}
func (*PEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_pcounter_42299f20fff80161, []int{1}
}
func (m *PEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PEvent.Unmarshal(m, b)
}
func (m *PEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PEvent.Marshal(b, m, deterministic)
}
func (dst *PEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PEvent.Merge(dst, src)
}
func (m *PEvent) XXX_Size() int {
	return xxx_messageInfo_PEvent.Size(m)
}
func (m *PEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_PEvent.DiscardUnknown(m)
}

var xxx_messageInfo_PEvent proto.InternalMessageInfo

func (m *PEvent) GetTyp() string {
	if m != nil {
		return m.Typ
	}
	return ""
}

func (m *PEvent) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PEvent) GetSeq() uint32 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *PEvent) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *PEvent) GetDir() string {
	if m != nil {
		return m.Dir
	}
	return ""
}

func (m *PEvent) GetTs() *timestamp.Timestamp {
	if m != nil {
		return m.Ts
	}
	return nil
}

func (m *PEvent) GetFillLevel() string {
	if m != nil {
		return m.FillLevel
	}
	return ""
}

func (m *PEvent) GetDwellTime() string {
	if m != nil {
		return m.DwellTime
	}
	return ""
}

func (m *PEvent) GetExpDwellTime() string {
	if m != nil {
		return m.ExpDwellTime
	}
	return ""
}

type PArea struct {
	Type                 string    `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id                   string    `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Label                string    `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Nodes                []float32 `protobuf:"fixed32,4,rep,packed,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PArea) Reset()         { *m = PArea{} }
func (m *PArea) String() string { return proto.CompactTextString(m) }
func (*PArea) ProtoMessage()    {}
func (*PArea) Descriptor() ([]byte, []int) {
	return fileDescriptor_pcounter_42299f20fff80161, []int{2}
}
func (m *PArea) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PArea.Unmarshal(m, b)
}
func (m *PArea) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PArea.Marshal(b, m, deterministic)
}
func (dst *PArea) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PArea.Merge(dst, src)
}
func (m *PArea) XXX_Size() int {
	return xxx_messageInfo_PArea.Size(m)
}
func (m *PArea) XXX_DiscardUnknown() {
	xxx_messageInfo_PArea.DiscardUnknown(m)
}

var xxx_messageInfo_PArea proto.InternalMessageInfo

func (m *PArea) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *PArea) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PArea) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *PArea) GetNodes() []float32 {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func init() {
	proto.RegisterType((*PCounter)(nil), "pcounter.PCounter")
	proto.RegisterType((*PEvent)(nil), "pcounter.PEvent")
	proto.RegisterType((*PArea)(nil), "pcounter.PArea")
}

func init() { proto.RegisterFile("pcounter.proto", fileDescriptor_pcounter_42299f20fff80161) }

var fileDescriptor_pcounter_42299f20fff80161 = []byte{
	// 424 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xdd, 0x8a, 0x13, 0x31,
	0x14, 0xa6, 0xd3, 0x76, 0x9c, 0x39, 0xeb, 0xae, 0x4b, 0x10, 0x09, 0x55, 0xb0, 0x56, 0x85, 0xe2,
	0xc5, 0x14, 0xd6, 0x27, 0xf0, 0xef, 0x42, 0xf0, 0x62, 0x09, 0x82, 0xe0, 0xcd, 0x92, 0x4e, 0xce,
	0xb6, 0x81, 0xcc, 0x64, 0x4c, 0xd2, 0xee, 0xd6, 0x87, 0xf3, 0xa1, 0x7c, 0x02, 0xc9, 0xdf, 0x56,
	0xf1, 0x66, 0xef, 0xce, 0xf7, 0x13, 0x4e, 0xbe, 0x8f, 0x03, 0x67, 0x43, 0xab, 0x77, 0xbd, 0x43,
	0xd3, 0x0c, 0x46, 0x3b, 0x4d, 0xaa, 0x8c, 0x67, 0xcf, 0x37, 0x5a, 0x6f, 0x14, 0xae, 0x02, 0xbf,
	0xde, 0x5d, 0xaf, 0x9c, 0xec, 0xd0, 0x3a, 0xde, 0x0d, 0xd1, 0xba, 0xf8, 0x55, 0x40, 0x75, 0xf9,
	0x21, 0xba, 0xc9, 0x53, 0xa8, 0x05, 0xee, 0x65, 0x8b, 0x57, 0x52, 0xd0, 0xd1, 0x7c, 0xb4, 0xac,
	0x59, 0x15, 0x89, 0xcf, 0x82, 0xcc, 0xa0, 0xda, 0x6a, 0xeb, 0x7a, 0xde, 0x21, 0x2d, 0xa2, 0x96,
	0xb1, 0xd7, 0x94, 0x6e, 0xb9, 0x93, 0xba, 0xa7, 0xe3, 0xa8, 0x65, 0xec, 0x35, 0xbf, 0xf4, 0xa7,
	0xee, 0x91, 0x4e, 0xa2, 0x96, 0x31, 0x39, 0x87, 0x71, 0xc7, 0x5b, 0x3a, 0x0d, 0xb4, 0x1f, 0xc3,
	0x16, 0x6e, 0xc4, 0x0d, 0x37, 0x48, 0xcb, 0xb4, 0x25, 0x61, 0xaf, 0x85, 0x4f, 0xb7, 0x5a, 0xd1,
	0x07, 0x51, 0xcb, 0x98, 0xbc, 0x81, 0xc2, 0x59, 0x5a, 0xcd, 0x47, 0xcb, 0x93, 0x8b, 0x59, 0x13,
	0x53, 0x37, 0x39, 0x75, 0xf3, 0x35, 0xa7, 0x66, 0x85, 0xb3, 0xe4, 0x15, 0x4c, 0x04, 0x77, 0x9c,
	0xd6, 0xf3, 0xf1, 0xf2, 0xe4, 0xe2, 0xbc, 0xb9, 0x6b, 0xef, 0xf2, 0xd3, 0x1e, 0x7b, 0xc7, 0x82,
	0x4a, 0x5e, 0xc3, 0x94, 0x1b, 0xe4, 0x96, 0x42, 0xb0, 0x3d, 0xfa, 0xcb, 0xf6, 0xce, 0x20, 0x67,
	0x51, 0x5d, 0xfc, 0x1e, 0x41, 0x19, 0xdf, 0xf9, 0x34, 0xee, 0x30, 0xa4, 0xe2, 0xfc, 0x48, 0xce,
	0xa0, 0x90, 0x22, 0xb5, 0x55, 0x48, 0xe1, 0x1d, 0x16, 0x7f, 0x84, 0x8a, 0x4e, 0x99, 0x1f, 0xc9,
	0x13, 0x28, 0xb7, 0x28, 0x37, 0x5b, 0x17, 0xba, 0x39, 0x65, 0x09, 0x79, 0xa7, 0x90, 0x26, 0x37,
	0x23, 0xa4, 0x49, 0x09, 0xcb, 0x7b, 0x25, 0x7c, 0x06, 0xf5, 0xb5, 0x54, 0xea, 0x0b, 0xee, 0x31,
	0x57, 0x75, 0x24, 0xbc, 0x2a, 0x6e, 0x50, 0x29, 0xff, 0x26, 0x54, 0x56, 0xb3, 0x23, 0x41, 0x16,
	0xf0, 0x10, 0x6f, 0x87, 0x8f, 0x77, 0x86, 0x3a, 0x18, 0xfe, 0xe1, 0x16, 0xdf, 0x60, 0x1a, 0x4a,
	0x20, 0x04, 0x26, 0xee, 0x30, 0x60, 0xca, 0x1c, 0xe6, 0xff, 0x42, 0x3f, 0x86, 0xa9, 0xe2, 0x6b,
	0x54, 0xe9, 0x32, 0x22, 0xf0, 0x6c, 0xaf, 0x05, 0x5a, 0x3a, 0x99, 0x8f, 0x97, 0x05, 0x8b, 0xe0,
	0xfd, 0xcb, 0xef, 0x2f, 0x36, 0xd2, 0x6d, 0x77, 0xeb, 0xa6, 0xd5, 0xdd, 0xca, 0x1e, 0x7a, 0x34,
	0x78, 0x1b, 0xaf, 0xf7, 0x2a, 0xf7, 0xbf, 0x2e, 0x03, 0x7e, 0xfb, 0x27, 0x00, 0x00, 0xff, 0xff,
	0x13, 0x67, 0x8e, 0xc0, 0xf7, 0x02, 0x00, 0x00,
}
