// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pcounter.proto

package proto_pcounter // import "github.com/synerex/proto_pcounter"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import duration "github.com/golang/protobuf/ptypes/duration"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// People Counter Service message
type PCounter struct {
	DeviceId             string               `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Hostname             string               `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Location             string               `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Timezone             string               `protobuf:"bytes,4,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Mac                  string               `protobuf:"bytes,5,opt,name=mac,proto3" json:"mac,omitempty"`
	Hardware             string               `protobuf:"bytes,6,opt,name=hardware,proto3" json:"hardware,omitempty"`
	Protocol             string               `protobuf:"bytes,7,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Ip                   string               `protobuf:"bytes,8,opt,name=ip,proto3" json:"ip,omitempty"`
	IpVpn                string               `protobuf:"bytes,9,opt,name=ip_vpn,json=ipVpn,proto3" json:"ip_vpn,omitempty"`
	Ts                   *timestamp.Timestamp `protobuf:"bytes,10,opt,name=ts,proto3" json:"ts,omitempty"`
	Data                 []*PEvent            `protobuf:"bytes,11,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PCounter) Reset()         { *m = PCounter{} }
func (m *PCounter) String() string { return proto.CompactTextString(m) }
func (*PCounter) ProtoMessage()    {}
func (*PCounter) Descriptor() ([]byte, []int) {
	return fileDescriptor_pcounter_944bb82e98d395cb, []int{0}
}
func (m *PCounter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PCounter.Unmarshal(m, b)
}
func (m *PCounter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PCounter.Marshal(b, m, deterministic)
}
func (dst *PCounter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PCounter.Merge(dst, src)
}
func (m *PCounter) XXX_Size() int {
	return xxx_messageInfo_PCounter.Size(m)
}
func (m *PCounter) XXX_DiscardUnknown() {
	xxx_messageInfo_PCounter.DiscardUnknown(m)
}

var xxx_messageInfo_PCounter proto.InternalMessageInfo

func (m *PCounter) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *PCounter) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *PCounter) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *PCounter) GetTimezone() string {
	if m != nil {
		return m.Timezone
	}
	return ""
}

func (m *PCounter) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func (m *PCounter) GetHardware() string {
	if m != nil {
		return m.Hardware
	}
	return ""
}

func (m *PCounter) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *PCounter) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *PCounter) GetIpVpn() string {
	if m != nil {
		return m.IpVpn
	}
	return ""
}

func (m *PCounter) GetTs() *timestamp.Timestamp {
	if m != nil {
		return m.Ts
	}
	return nil
}

func (m *PCounter) GetData() []*PEvent {
	if m != nil {
		return m.Data
	}
	return nil
}

type PEvent struct {
	Typ                  string               `protobuf:"bytes,1,opt,name=typ,proto3" json:"typ,omitempty"`
	Id                   string               `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Seq                  uint32               `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Height               uint32               `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Dir                  string               `protobuf:"bytes,5,opt,name=dir,proto3" json:"dir,omitempty"`
	Ts                   *timestamp.Timestamp `protobuf:"bytes,6,opt,name=ts,proto3" json:"ts,omitempty"`
	TsExit               *timestamp.Timestamp `protobuf:"bytes,7,opt,name=ts_exit,json=tsExit,proto3" json:"ts_exit,omitempty"`
	FillLevel            uint32               `protobuf:"varint,8,opt,name=fillLevel,proto3" json:"fillLevel,omitempty"`
	DwellTime            float32              `protobuf:"fixed32,9,opt,name=dwellTime,proto3" json:"dwellTime,omitempty"`
	ExpDwellTime         float32              `protobuf:"fixed32,10,opt,name=expDwellTime,proto3" json:"expDwellTime,omitempty"`
	ObjectId             uint32               `protobuf:"varint,11,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PEvent) Reset()         { *m = PEvent{} }
func (m *PEvent) String() string { return proto.CompactTextString(m) }
func (*PEvent) ProtoMessage()    {}
func (*PEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_pcounter_944bb82e98d395cb, []int{1}
}
func (m *PEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PEvent.Unmarshal(m, b)
}
func (m *PEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PEvent.Marshal(b, m, deterministic)
}
func (dst *PEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PEvent.Merge(dst, src)
}
func (m *PEvent) XXX_Size() int {
	return xxx_messageInfo_PEvent.Size(m)
}
func (m *PEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_PEvent.DiscardUnknown(m)
}

var xxx_messageInfo_PEvent proto.InternalMessageInfo

func (m *PEvent) GetTyp() string {
	if m != nil {
		return m.Typ
	}
	return ""
}

func (m *PEvent) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PEvent) GetSeq() uint32 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *PEvent) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *PEvent) GetDir() string {
	if m != nil {
		return m.Dir
	}
	return ""
}

func (m *PEvent) GetTs() *timestamp.Timestamp {
	if m != nil {
		return m.Ts
	}
	return nil
}

func (m *PEvent) GetTsExit() *timestamp.Timestamp {
	if m != nil {
		return m.TsExit
	}
	return nil
}

func (m *PEvent) GetFillLevel() uint32 {
	if m != nil {
		return m.FillLevel
	}
	return 0
}

func (m *PEvent) GetDwellTime() float32 {
	if m != nil {
		return m.DwellTime
	}
	return 0
}

func (m *PEvent) GetExpDwellTime() float32 {
	if m != nil {
		return m.ExpDwellTime
	}
	return 0
}

func (m *PEvent) GetObjectId() uint32 {
	if m != nil {
		return m.ObjectId
	}
	return 0
}

type PCounters struct {
	Pcs                  []*PCounter `protobuf:"bytes,1,rep,name=pcs,proto3" json:"pcs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PCounters) Reset()         { *m = PCounters{} }
func (m *PCounters) String() string { return proto.CompactTextString(m) }
func (*PCounters) ProtoMessage()    {}
func (*PCounters) Descriptor() ([]byte, []int) {
	return fileDescriptor_pcounter_944bb82e98d395cb, []int{2}
}
func (m *PCounters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PCounters.Unmarshal(m, b)
}
func (m *PCounters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PCounters.Marshal(b, m, deterministic)
}
func (dst *PCounters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PCounters.Merge(dst, src)
}
func (m *PCounters) XXX_Size() int {
	return xxx_messageInfo_PCounters.Size(m)
}
func (m *PCounters) XXX_DiscardUnknown() {
	xxx_messageInfo_PCounters.DiscardUnknown(m)
}

var xxx_messageInfo_PCounters proto.InternalMessageInfo

func (m *PCounters) GetPcs() []*PCounter {
	if m != nil {
		return m.Pcs
	}
	return nil
}

type Retrieve struct {
	From                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Duration             *duration.Duration   `protobuf:"bytes,2,opt,name=duration,proto3" json:"duration,omitempty"`
	Result               *PCounters           `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Retrieve) Reset()         { *m = Retrieve{} }
func (m *Retrieve) String() string { return proto.CompactTextString(m) }
func (*Retrieve) ProtoMessage()    {}
func (*Retrieve) Descriptor() ([]byte, []int) {
	return fileDescriptor_pcounter_944bb82e98d395cb, []int{3}
}
func (m *Retrieve) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Retrieve.Unmarshal(m, b)
}
func (m *Retrieve) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Retrieve.Marshal(b, m, deterministic)
}
func (dst *Retrieve) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Retrieve.Merge(dst, src)
}
func (m *Retrieve) XXX_Size() int {
	return xxx_messageInfo_Retrieve.Size(m)
}
func (m *Retrieve) XXX_DiscardUnknown() {
	xxx_messageInfo_Retrieve.DiscardUnknown(m)
}

var xxx_messageInfo_Retrieve proto.InternalMessageInfo

func (m *Retrieve) GetFrom() *timestamp.Timestamp {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Retrieve) GetDuration() *duration.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

func (m *Retrieve) GetResult() *PCounters {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*PCounter)(nil), "pcounter.PCounter")
	proto.RegisterType((*PEvent)(nil), "pcounter.PEvent")
	proto.RegisterType((*PCounters)(nil), "pcounter.PCounters")
	proto.RegisterType((*Retrieve)(nil), "pcounter.Retrieve")
}

func init() { proto.RegisterFile("pcounter.proto", fileDescriptor_pcounter_944bb82e98d395cb) }

var fileDescriptor_pcounter_944bb82e98d395cb = []byte{
	// 521 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xd1, 0x6e, 0xd3, 0x3e,
	0x14, 0xc6, 0xd5, 0x74, 0xcb, 0x52, 0xe7, 0xbf, 0x69, 0xf2, 0x5f, 0x20, 0x53, 0x10, 0x94, 0xc2,
	0x45, 0x05, 0x52, 0x2a, 0x3a, 0xf1, 0x02, 0xb0, 0x5d, 0x4c, 0xe2, 0x62, 0xb2, 0x10, 0x17, 0xdc,
	0x54, 0x69, 0x7c, 0xda, 0x1a, 0x25, 0xb1, 0xb1, 0xdd, 0xae, 0xe3, 0x61, 0x78, 0x14, 0xae, 0x78,
	0x30, 0xe4, 0xe3, 0xb8, 0x03, 0x26, 0x4d, 0xdc, 0xf9, 0x7c, 0xdf, 0x77, 0x9c, 0x93, 0x9f, 0x6d,
	0x72, 0xa2, 0x2b, 0xb5, 0x69, 0x1d, 0x98, 0x42, 0x1b, 0xe5, 0x14, 0xcd, 0x62, 0x3d, 0x7c, 0xb6,
	0x52, 0x6a, 0x55, 0xc3, 0x14, 0xf5, 0xc5, 0x66, 0x39, 0x75, 0xb2, 0x01, 0xeb, 0xca, 0x46, 0x87,
	0xe8, 0xf0, 0xe9, 0xdf, 0x01, 0xb1, 0x31, 0xa5, 0x93, 0xaa, 0x0d, 0xfe, 0xf8, 0x47, 0x42, 0xb2,
	0xab, 0xf7, 0x61, 0x37, 0xfa, 0x98, 0x0c, 0x04, 0x6c, 0x65, 0x05, 0x73, 0x29, 0x58, 0x6f, 0xd4,
	0x9b, 0x0c, 0x78, 0x16, 0x84, 0x4b, 0x41, 0x87, 0x24, 0x5b, 0x2b, 0xeb, 0xda, 0xb2, 0x01, 0x96,
	0x04, 0x2f, 0xd6, 0xde, 0xab, 0x55, 0x85, 0xfb, 0xb2, 0x7e, 0xf0, 0x62, 0xed, 0x3d, 0x3f, 0xd4,
	0x37, 0xd5, 0x02, 0x3b, 0x08, 0x5e, 0xac, 0xe9, 0x29, 0xe9, 0x37, 0x65, 0xc5, 0x0e, 0x51, 0xf6,
	0x4b, 0xfc, 0x4a, 0x69, 0xc4, 0x75, 0x69, 0x80, 0xa5, 0xdd, 0x57, 0xba, 0xda, 0x7b, 0x38, 0x74,
	0xa5, 0x6a, 0x76, 0x14, 0xbc, 0x58, 0xd3, 0x13, 0x92, 0x48, 0xcd, 0x32, 0x54, 0x13, 0xa9, 0xe9,
	0x03, 0x92, 0x4a, 0x3d, 0xdf, 0xea, 0x96, 0x0d, 0x50, 0x3b, 0x94, 0xfa, 0x93, 0x6e, 0xe9, 0x2b,
	0x92, 0x38, 0xcb, 0xc8, 0xa8, 0x37, 0xc9, 0x67, 0xc3, 0x22, 0xb0, 0x29, 0x22, 0x9b, 0xe2, 0x63,
	0x84, 0xc7, 0x13, 0x67, 0xe9, 0x4b, 0x72, 0x20, 0x4a, 0x57, 0xb2, 0x7c, 0xd4, 0x9f, 0xe4, 0xb3,
	0xd3, 0x62, 0x7f, 0x08, 0x57, 0x17, 0x5b, 0x68, 0x1d, 0x47, 0x77, 0xfc, 0x33, 0x21, 0x69, 0x10,
	0xfc, 0xdf, 0xb8, 0x1b, 0xdd, 0x81, 0xf3, 0x4b, 0x9c, 0x4a, 0x74, 0xb4, 0x12, 0x29, 0x7c, 0xc2,
	0xc2, 0x57, 0x44, 0x74, 0xcc, 0xfd, 0x92, 0x3e, 0x24, 0xe9, 0x1a, 0xe4, 0x6a, 0xed, 0x90, 0xcd,
	0x31, 0xef, 0x2a, 0x9f, 0x14, 0xd2, 0x44, 0x32, 0x42, 0x9a, 0x6e, 0xf4, 0xf4, 0x9f, 0x46, 0x3f,
	0x23, 0x47, 0xce, 0xce, 0x61, 0x27, 0x1d, 0x82, 0xba, 0xbf, 0x21, 0x75, 0xf6, 0x62, 0x27, 0x1d,
	0x7d, 0x42, 0x06, 0x4b, 0x59, 0xd7, 0x1f, 0x60, 0x0b, 0x35, 0x92, 0x3c, 0xe6, 0xb7, 0x82, 0x77,
	0xc5, 0x35, 0xd4, 0xb5, 0xef, 0x43, 0xa6, 0x09, 0xbf, 0x15, 0xe8, 0x98, 0xfc, 0x07, 0x3b, 0x7d,
	0xbe, 0x0f, 0x10, 0x0c, 0xfc, 0xa1, 0xf9, 0xdb, 0xa5, 0x16, 0x5f, 0xa0, 0x72, 0xfe, 0x76, 0xe5,
	0xb8, 0x7f, 0x16, 0x84, 0x4b, 0x31, 0x7e, 0x43, 0x06, 0xf1, 0x1a, 0x7a, 0xf2, 0x7d, 0x5d, 0x59,
	0xd6, 0x43, 0xf0, 0xf4, 0x37, 0xf0, 0x5d, 0x82, 0x7b, 0x7b, 0xfc, 0xbd, 0x47, 0x32, 0x0e, 0xce,
	0x48, 0xd8, 0x02, 0x2d, 0xc8, 0xc1, 0xd2, 0xa8, 0x06, 0xe1, 0xdf, 0xff, 0xbb, 0x98, 0xa3, 0x6f,
	0x49, 0x16, 0x5f, 0x02, 0x9e, 0x4f, 0x3e, 0x7b, 0x74, 0xa7, 0xe7, 0xbc, 0x0b, 0xf0, 0x7d, 0x94,
	0xbe, 0x26, 0xa9, 0x01, 0xbb, 0xa9, 0x1d, 0x9e, 0x61, 0x3e, 0xfb, 0xff, 0xee, 0x70, 0x96, 0x77,
	0x91, 0x77, 0x2f, 0x3e, 0x3f, 0x5f, 0x49, 0xb7, 0xde, 0x2c, 0x8a, 0x4a, 0x35, 0x53, 0x7b, 0xd3,
	0x82, 0x81, 0x5d, 0x78, 0x89, 0xf3, 0xd8, 0xb6, 0x48, 0xb1, 0x3e, 0xfb, 0x15, 0x00, 0x00, 0xff,
	0xff, 0xff, 0xbf, 0xe7, 0xb3, 0xe4, 0x03, 0x00, 0x00,
}
